name: TimezoneAlarm
options:
  bundleIdPrefix: com.timezonealarm
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
packages: {}
targets:
  TimezoneAlarm:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TimezoneAlarm
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.timezonealarm.app
        INFOPLIST_FILE: TimezoneAlarm/Info.plist
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
    info:
      path: TimezoneAlarm/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
  TimezoneAlarmTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TimezoneAlarmTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.timezonealarm.appTests
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
    dependencies:
      - target: TimezoneAlarm

